### ISSUE TITLE
Could not start debugger

### ISSUE THREAD

**Issue by cipri-tom** [jsargiot/ninja-debugger-plugin#1]
I know issues are supposed to include at least some information, but I have no idea where to get it from. That is all I get when I click "Addins > Debug file" : The debugger could not be started. Please tell me what to do in order to give you more information
Ninja version: 2.1.1

**Comment by jsargiot** [comment]
Hi Ciprian,

The isssue seems to be with the configuration of the python path. Go to Edit -> Preferences in the Executable tab check that python path points to your python executable.

If the issue persists, please let me know.

Regards

**Comment by cipri-tom** [comment]
Hi Joaquin,

I verified what you've said, and updated the path to my python executable. It was just _python_ and updated it to the result of the bash comand _which python_, namely to _/urs/bin/python_ .

I don understand why that would be the problem, as I thought that was for the programs, which work. It's just the debugger that doesn't start

**Comment by eddyp** [comment]
I have run into the same issue.
Maybe the plugin should check python exists or something of that sort and fail more graciously?

Also, taking into account my program runs fine when started with Run Project, I think the failure of the debugger to execute in the same condition should be considered a bug.

Also note that the workaround you proposed before did not work for me until there was a restart.

**Comment by jsargiot** [comment]
You are right, i've been kind of busy lately to make improvements.

If any of you feel like making it better just fork :)

Thanks for the feedback

## 

Joaquin Sargiotto

**Comment by jsargiot** [comment]
The latest version should address this issue. Please check.
